### ISSUE TITLE
Yesod hangs on marshalling errors with MongoDB

### ISSUE THREAD

**Issue by m-blazejczyk** [yesodweb/persistent#379] opened 2015-03-25 19:51 UTC
Hi,

This has happened to me twice already, in two different places.  One of the cases is actually easy to reproduce so I am reporting it here.  I think it points towards a problem in database marshaling.  In both cases, there was a hidden error or exception that caused the page not to load.  In the console I would only get the original page request and then nothin, no errors, and the page never loads.  The first time it happened it took me about 2 hours of changing code in all kinds of ways to finally see an Internal Server Error with a message that pointed me towards a solution.

To reproduce, create a fresh Yesod installation with MongoDB as the backend.  Create a persistent data type like so:

```
EnumTest
    lookupId Int64
    name Text
    myOption MyEnum
    UniqueEnumTest lookupId
```

MyEnum is a data type defined like so (I directly followed the Yesod book):

``` haskell
data MyEnum = OptionOne | OptionTwo | OptionThree
    deriving (Show, Read, Eq)
derivePersistField "MyEnum"
```

Then modify the default getHomeR handler to insert the record into the database:

``` haskell
getHomeR :: Handler Html
getHomeR = do
    (formWidget, formEnctype) <- generateFormPost sampleForm
    record <- runDB $ insert $ EnumTest 1 "Test" OptionOne
    let submission = Nothing :: Maybe (FileInfo, Text)
        handlerName = "getHomeR" :: Text
    defaultLayout $ do
        aDomId <- newIdent
        setTitle "Welcome To Yesod!"
        $(widgetFile "homepage")
```

Here's the data record in this case:

```
{
    "_id" : ObjectId("55130d53aae39e14ec000000"),
    "lookupId" : NumberLong(1),
    "name" : "Test",
    "myOption" : "OptionOne"
}
```

To check if it works, replace the `runDB $ insert ...` line above with:

``` haskell
(Entity _ enumTest) <- runDB $ getBy404 $ UniqueEnumTest 1
```

It will work fine.

However, when you go into the database and change the value of the `myOption` field to a string that does NOT match any of the allowed options, Yesod will freeze when you try to refresh the page.  The only thing you'll get in the console will be:

```
GET /
  Accept: text/html, application/xhtml+xml, */*
```

Thank you so much,
Michal

**Comment by m-blazejczyk** [comment] 2015-04-29 02:40
Hi,

Since I have received no feedback...  I don't necessarily need a solution, but can someone help me by suggesting how I can debug when this occurs?  In other words, how I can get the error message from the backend?  I am currently stuck once again, and I'm running in circles commenting out various bits and pieces of code...

Thank you in advance,
Michal

**Comment by gregwebs** [comment] 2015-04-29 03:47
Can we produce a test case for this by having 2 models that share the same table (using sql=) ?

I don't know why the error message does not get propogated other than the case of an infinte loop. If you have not tried it yet, you should run your app directly without yesod devel and see if the error shows up.

**Comment by m-blazejczyk** [comment] 2015-04-29 18:04
Hi Greg,

This issue is not limited to this particular scenario.  It seems that whenever I get a runtime error someplace in my application (usually while interacting with the database), they don't get reported but my app goes into an infinite loop.

I've just ran my app directly, and it's happening as well, in completely different code.  I have two pages that are based on database records, and one of them loads fine while the other one gets stuck.  No errors are displayed in the console.

Is there a way to turn on additional logging that could help here?

Thank you,
Michal

**Comment by gregwebs** [comment] 2015-04-29 18:07
Some errors are being shown correctly?

do you see high CPU usage or some indication that the app is stuck in a loop?

**Comment by m-blazejczyk** [comment] 2015-04-29 18:12
Hi,

No, there is no spike in CPU usage, and no errors whatsoever.  But please
let me test this again tonight at home where my database contents are
slightly different than here at work.  I will get back to you.

Best,
Michal

**Comment by m-blazejczyk** [comment] 2015-04-30 02:13
Hi,

I can confirm that the same symptoms are happening in my home installation.

Do you have any other ideas regarding how to debug this further?

Best,
Michal

**Comment by gregwebs** [comment] 2015-04-30 13:07
I am still not certain what the problem is. It seems like it is a problem with persistent, but then you seem to report that it is not.

```
This issue is not limited to this particular scenario. It seems that whenever I get a runtime error someplace in my application (usually while interacting with the database)
```

From this comment it seems like you would have an issue seeing the error show up just from intentionally throwing an exception in your code. Is that the case?

**Comment by m-blazejczyk** [comment] 2015-04-30 16:44
Hi,

Yes, sorry, I was being to broad...  It does always happen in persistent
code.  I've just tried putting an "error" call in my handler, and it did
get displayed properly as Internal Server Error.  What I meant was that the
persistent issue is not limited to what the original bug report describes -
I've had it happen to me 3-4 times already in different persistent-related
contexts.  Also, it is also always somehow related to the contents of the
database, e.g. the same handler code may work fine with some records but
not others, suggesting, as I originally assumed, marshaling errors.

Is there any additional error handling that I could add to my handler to
see what's going on?  Additional logging?

Thank you,
Michal

**Comment by gregwebs** [comment] 2015-04-30 17:04
You could log something before and after every runDB

**Comment by parsonsmatt** [comment] 2020-02-13 22:23
I attempted to recreate this issue by calling `fromPersistValue` for a derived type with the wrong value and it worked immediately.

I'm going to close this out. If anyone experiences this in the future, please post a minimal reproduction.

**Closed by parsonsmatt** 2020-02-13 22:23 UTC
Labels: mongoDB
