### ISSUE TITLE
MySQL: ByteString and BLOBs

### ISSUE THREAD

**Issue by agrafix** [yesodweb/persistent#122] opened 2013-04-11 12:47 UTC
Currently the MySQL Migration creates a BLOB field for ByteStrings. However, if the ByteString is larger than 64kB it get's cut-off, without any warning. Maybe implement MEDIUMBLOB/LARGEBLOB or display warnings?

**Comment by MaxGabriel** [comment] 2015-05-25 04:22
Does Persistent currently check fields for being longer than the storable value? If not, I think this probably best addressed by using MySQL/InnoDB's [strict mode](http://dev.mysql.com/doc/refman/5.6/en/innodb-parameters.html#sysvar_innodb_strict_mode), which raises errors when a value is too large to be stored. 

As for `MEDIUMBLOB`/`LONGBLOB`, those can be used by specifying the `sqltype`:

```
Bar
    test ByteString
    testMedium ByteString sqltype=MEDIUMBLOB
    testLong ByteString sqltype=LONGBLOB
```

```
mysql> SHOW CREATE TABLE bar\G
*************************** 1. row ***************************
       Table: bar
Create Table: CREATE TABLE `bar` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `test` blob NOT NULL,
  `test_medium` mediumblob NOT NULL,
  `test_long` longblob NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

Potentially it would be a good idea to enable strict mode in the scaffolding or something (it's a really good default, imo), but otherwise I think this can be closed.

**Comment by gregwebs** [comment] 2015-05-25 04:44
> Does Persistent currently check fields for being longer than the storable value?

No.

I don't think this should be closed. What is being done for Text? The behavior should be the same.

**Comment by MaxGabriel** [comment] 2015-05-25 05:02
`Text` is handled the same way; it defaults to the MySQL `TEXT` type which has the [same maximum length](https://dev.mysql.com/doc/refman/5.6/en/blob.html) as `BLOB` (same with `MEDIUMTEXT`/`MEDIUMBLOB` and `LONGTEXT`/`LONGBLOB`).

```
Baz
    test Text
    testMedium Text sqltype=MEDIUMTEXT
    testLong Text sqltype=LONGTEXT
```

```
mysql> SHOW CREATE TABLE baz\G
*************************** 1. row ***************************
       Table: baz
Create Table: CREATE TABLE `baz` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `test` text NOT NULL,
  `test_medium` mediumtext NOT NULL,
  `test_long` longtext NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

**Comment by gregwebs** [comment] 2015-05-25 13:16
Ok, I agree the current behavior is correct if strict mode produces an error that is logged in Haskell at the error level or turned into an exception.

**Comment by MaxGabriel** [comment] 2015-05-25 18:54
@gregwebs I can confirm that an exception is thrown. Without strict mode the data is truncated, with it enabled (`SET GLOBAL sql_mode = 'STRICT_ALL_TABLES';`) I get the following exception:

```
ConnectionError {errFunction = "query", errNumber = 1406, errMessage = "Data too long for column 'test' at row 1"} @(yesod_Her3bQpHkRkDLXxJous6w5:Yesod.Core.Class.Yesod ./Yesod/Core/Class/Yesod.hs:539:5)
```

Roughly what code I used to test:


```haskell
{-# LANGUAGE ScopedTypeVariables #-} 
import qualified Data.ByteString as BS

getHomeR :: Handler Html
getHomeR = do

    let big = duplicateUpToSize "bytestring" 65535
    
    (void $ runDB $ insert $ Bar big big big) `catch` \(e :: SomeException) -> do
        traceM $ "Exception is" ++ show e
        return ()


duplicateUpToSize :: ByteString -> Int -> ByteString
duplicateUpToSize bs int = if BS.length bs > int then bs else duplicateUpToSize (bs <> bs) int
```

```
Bar
    test ByteString
    testMedium ByteString sqltype=MEDIUMBLOB
    testLong ByteString sqltype=LONGBLOB
```

**Comment by gregwebs** [comment] 2015-05-25 19:01
That looks like a good result to me. Where can we document the need for strict mode such that someone would see it? Putting something in the scaffolding is good, but that would only be for yesod users.

**Comment by MaxGabriel** [comment] 2015-05-27 05:11
@gregwebs I'm not sure, tbh. Maybe as a callout or short section titled "Backend-Specific Quirks" or "Database Configuration" or something, within an article or wiki page about integrating Persist manually w/o the scaffolding? Currently I think the only place like that is the Yesod Book, though. If there was sample code giving the best-practice way to use Persistent in a script or something like Scotty, it could be used there?

Whatever ends up addressing this could also mention enabling Foreign Key constraints for SQLite, since there's been interest in that from several Persistent users and it's in the same vein of ensuring data integrity.

It could go in a wiki page specifically about database configuration, but I feel like people would be less likely to see it.

**Comment by MaxGabriel** [comment] 2015-08-16 13:21
Added a [wiki page](https://github.com/yesodweb/persistent/wiki/Database-Configuration) about this.

**Comment by MaxGabriel** [comment] 2015-08-16 14:47
When I looked into this before I figured that the `mysql` package's `InitCommand` was the right way to enable strict mode, but ran into this issue https://github.com/bos/mysql/issues/16. Just submitted a PR fixing that: https://github.com/bos/mysql/pull/17

**Comment by MaxGabriel** [comment] 2015-08-29 17:25
The next version of the scaffolding will enable MySQL strict mode by default, which would prevent this from happening (see yesodweb/yesod-scaffold/pull/94). Thanks for reporting the issue!

**Closed by MaxGabriel** 2015-08-29 17:25 UTC
Labels: MySQL
