### ISSUE TITLE
not using WAL mode means persistent-sqlite sites are less robust than would be expected

### ISSUE THREAD

**Issue by joeyh** [yesodweb/persistent#363] opened 2015-02-18 18:54 UTC
Simply reading from a sqlite database can crash with BUSY if there's another connection performing a write at the same time.

I noticed these problems when using persistent-sqlite with multiple processes that do heavy read+write to a shared database. It's probably much less evident if using sqlite in the backend of a website that doesn't involve many writes.

I don't have experience with yesod's use of persistent, so I don't know if yesod sites have this problem. If yesod opens a single connection to the database, and all threads use this connection, that would avoid the problem. If each thread opens a new database connection, yesod sites would be affected.

The solution seems to be WAL mode. http://www.sqlite.org/wal.html

I think that persistent-sqlite should at least make it easy to enter WAL mode and document that it makes things more robust. But really, does it make sense for it to not use WAL mode by default?

I expected this stuff to be solid, not apparently solid until you put it under load.

**Comment by snoyberg** [comment] 2015-02-25 05:29
I see no problem with turning on WAL by default.

For the record: persistent-sqlite is *not* intended to be robust for a server deployment, it's meant for specific use cases (like a non-concurrent application) and easy testing. But if we can make it a bit better for the high-load case, I don't see a reason to avoid doing so.

**Comment by snoyberg** [comment] 2015-02-25 05:36
I've just pushed a commit to turn this on, but have only tested it lightly. Could you give it a spin?

**Comment by emmanueltouzery** [comment] 2015-03-16 05:31
I'm using persistent-sqlite in gui apps as a datastore and prefer a single data file rather than three (so the user can back up, use the file picker to open and save files). Can I get a single easy function call to disable wal? Because then data is spread over three files.

**Comment by snoyberg** [comment] 2015-03-16 06:08
Reading through the docs, it seems like the WAL log is just a temporary file, and won't be needed for persistence, but I could be mistaken. Anyway, regarding API for this, there are two options:

1. Embed the WAL setting inside the connection string, e.g. "WAL=off foo.sqlite3"
2. Add NoWal versions of `createSqlitePool`, `withSqlitePool`, and `withSqliteConn`

I lean towards the former, but it's a slight preference. There's also the question of whether WAL should be on or off by default, and I lean towards it being on by default since that seems to be the more common use case. But I'm open to discussion on both fronts.

**Comment by emmanueltouzery** [comment] 2015-03-16 06:52
aha didn't know about the connection string, seems like a good way indeed! Hopefully it works fine also with older SQLite versions but I'd be shocked if that's not the case.

Otherwise I think the other files are not temporary, I was googling that several days ago.
Also in the wal.html link it's written "There is an additional quasi-persistent "-wal" file and "-shm" shared memory file associated with each database, which can make SQLite less appealing for use as an application file-format."

Now, what they exactly mean by "quasi persistent" I'm not sure :-) but I'm happy if the connection string solution works. I have yet to upgrade persistent so I'll see when I do.

**Comment by snoyberg** [comment] 2015-03-16 07:42
What I meant is that we cam implement that in  persistent, but it doesn't
work yet.

**Comment by snoyberg** [comment] 2015-03-16 08:01
@emmanueltouzery I've just pushed a commit that adds the `WAL=off ` functionality, can you give it a try and see if it addresses your use case?

**Comment by emmanueltouzery** [comment] 2015-03-16 08:02
sorry it'll be some time before I can make it I think. I'll try before next week...

**Comment by snoyberg** [comment] 2015-03-16 08:02
I'm still waiting on review of the feature itself by @joeyh anyway, so I have no urgency getting this out the door.

**Comment by snoyberg** [comment] 2015-04-21 04:52
This has already been released to Hackage. Closing issue, please reopen if there are problems.

**Closed by snoyberg** 2015-04-21 04:52 UTC

**Comment by emmanueltouzery** [comment] 2015-06-22 19:58
well my code was using `open` and then `wrapConnection` and I was setting up a custom logger. Now if I don't want WAL then I can't use `wrapConnection` anymore: I must go through `open'`. Looking at the source that means I must go through `withSqliteConn` or `withSqlitePool`.

The pool looks overkill (remember it's a fat client app, single user, single connection), and the other one besides that it seems I can't set up a logger, I'm also a bit frightened by the documentation [there](http://www.yesodweb.com/blog/2011/08/persistent-0-6-0) which states that the connection is ran in a single transaction (I'm holding the connection for the runtime of the app in my case -- that means any crash or poweroff would loose the whole user session).

So can I get no WAL and a logger and the behaviour with transactions as it was with my previous setup?

PS: my case is really pretty special as I'm using persistent-sqlite to connect against a SQLcipher database. I see now that the PRAGMA that persistent runs to enable WAL in fact fails and drops my connection because I could not yet unlock the database by entering the password (which I must do through a PRAGMA just after connecting and before running any queries). So this turns out to be quite a lot more than a cosmetic issue to me at this point:
`SQLite3 returned ErrorNotAConnection while attempting to perform prepare "PRAGMA journal_mode=WAL;": file is encrypted or is not a database`

**Comment by emmanueltouzery** [comment] 2015-06-22 21:04
hmm well actually looking at this again, with some refactoring on my side I could unlock the DB before I call `wrapConnection`. So I'm just left with the cosmetic problem of the WAL that I'm not sure how to disable if I can't use `wrapConnection` directly.

**Comment by emmanueltouzery** [comment] 2015-06-25 07:35
well I modified my app so that it unlocks the connection before I call `wrapConnection` and also I set back the SQLite journal mode to `delete` immediately after I call `wrapConnection` and that works for me. Note that with WAL, after the app quit, i had three files on disk, two of non-zero size, so it was a regression as far as I was concerned.
