### ISSUE TITLE
Qualify table with database name

### ISSUE THREAD

**Issue by maxigit** [yesodweb/persistent#635] opened 2016-11-17 09:19 UTC
Is there a way to use persistent across different database?
I tried qualifying the using `sqlname=db.table` but it's seen as a table name.
I also tried

    sqlname=db`.`table

But the backticks are escaped . I understand this is a normal behavior chances is are that if you find a `.` in a table name, it's qualified table rather than a name with dot in it.

**Comment by parsonsmatt** [comment] 2020-02-14 00:40
Closing as a duplicate of #93 

Note that my library [`persistent-typed-db`](https://hackage.haskell.org/package/persistent-typed-db) handles this use case pretty well.

**Closed by parsonsmatt** 2020-02-14 00:40 UTC

**Comment by maxigit** [comment] 2020-02-19 17:12
If I understand correctly, your library allows to have two access two db
using two different backend in safe way, but doesn't allow
to mix them in one query, which is needed when doing a join between two
tables belonging to different databases.

Am I right ?

**Comment by parsonsmatt** [comment] 2020-02-19 17:30
That's correct.

**Comment by maxigit** [comment] 2020-02-19 17:34
In that case could we reopen the ticket ? In theory it just mean allowing '.' in table names.
The result is a simpler and more powerful solution that `persisent-typed-db` and as safe.

**Comment by parsonsmatt** [comment] 2020-02-19 17:39
I closed the ticket because it's a duplicate of #93 , not because my library subsumes all the use cases. I definitely want to implement schema information in entities!

**Comment by maxigit** [comment] 2020-02-19 17:43
Sorry, I misunderstood.
