### ISSUE TITLE
Table not found when using mkPersistWith

### ISSUE THREAD

**Issue by erichhasl** [yesodweb/persistent#1345] opened 2021-12-02 22:57 UTC
My models are split into two files. I use template haskell in both, to generate persistent entity definitions, migrations and data types. To make sure `ForeignKey`s are properly created when referencing models from the first file in the second. I tried to use `mkPersistWith`  in the second file and pass in the list of `EntityDef`s of the first file. This results in a runtime error though:

```
Table not found: Person
```

This is the setup:

```
{-# LANGUAGE OverloadedStrings #-}

module Main where

import Scheme1
import Scheme2

import Control.Monad.Logger (runStdoutLoggingT, LoggingT)
import Database.Persist
import Database.Persist.Postgresql

main :: IO ()
main = runStdoutLoggingT $ withPostgresqlPool "dbname=testdb" 1 $ liftSqlPersistMPool $ do
    runMigration migrate1
    runMigration migrate2
```
and the two model files are as follows:
```
{-# LANGUAGE TemplateHaskell            #-}
{-# LANGUAGE QuasiQuotes                #-}
{-# LANGUAGE TypeFamilies               #-}
{-# LANGUAGE MultiParamTypeClasses      #-}
{-# LANGUAGE GADTs                      #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE RecordWildCards            #-}
{-# LANGUAGE FlexibleInstances          #-}
{-# LANGUAGE OverloadedStrings          #-}
{-# LANGUAGE DerivingStrategies         #-}
{-# LANGUAGE StandaloneDeriving         #-}
{-# LANGUAGE UndecidableInstances       #-}
{-# LANGUAGE DataKinds                  #-}

module Scheme1 where

import qualified Database.Persist.TH as PTH

PTH.share [ PTH.mkPersist PTH.sqlSettings
          , PTH.mkEntityDefList "tables1"
          , PTH.mkMigrate "migrate1"] [PTH.persistLowerCase|
    Person
        name String
        age Int
        deriving Show Read
|]
```
and
```
{-# LANGUAGE TemplateHaskell            #-}
{-# LANGUAGE QuasiQuotes                #-}
{-# LANGUAGE TypeFamilies               #-}
{-# LANGUAGE MultiParamTypeClasses      #-}
{-# LANGUAGE GADTs                      #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE RecordWildCards            #-}
{-# LANGUAGE FlexibleInstances          #-}
{-# LANGUAGE OverloadedStrings          #-}
{-# LANGUAGE DerivingStrategies         #-}
{-# LANGUAGE StandaloneDeriving         #-}
{-# LANGUAGE UndecidableInstances       #-}
{-# LANGUAGE DataKinds                  #-}

module Scheme2 where

import Scheme1

import qualified Database.Persist.TH as PTH

PTH.share [ PTH.mkPersistWith PTH.sqlSettings tables1
          , PTH.mkEntityDefList "tables2"
          , PTH.mkMigrate "migrate2"] [PTH.persistLowerCase|
    Cookie
        flavour String
        owner PersonId
        deriving Show Read
|]

```
I suspect there is a bug somewhere. Replacing `mkPersistWith` with `mkPersist` gets rid of the runtime error, but does not create `ForeignKey`s.

Tried this in stackage LTS 18.18 so persistent version 2.13.2.1.

**Comment by parsonsmatt** [comment] 2022-01-06 14:58
I think this is a duplicate of #1307. Thanks for the reproduction!

**Closed by parsonsmatt** 2022-01-06 14:58 UTC
