### ISSUE TITLE
MySQL default encoding

### ISSUE THREAD

**Issue by alexkazik** [yesodweb/persistent#813] opened 2018-06-01 10:31 UTC
The default encoding persistent choses for all text-like columns is utf8.
The problem is that MySQL's utf8 is only capable to store the BMP characters (i.e. up to three byte UTF-8 characters).

There is a new character encoding called utf8mb4 which is what the rest of the world calls UTF-8.

It was added in [MySQL 5.5.3 (2010-03-24)](https://dev.mysql.com/doc/relnotes/mysql/5.5/en/news-5-5-3.html).

(Also sometimes later utf8 was renamed to utf8mb3 to represent it better, and utf8 is kept as an alias for it.)

A conversion from utf8 to utf8mb4 can always be done.

I'd like to either have an option to select the default or simply changing it (MySQL.hs:773,775).
Currently I have to write all sql types by hand to accomplish that.

That the connection is also utf8 be default does not really help either, but that setting can be modified ("mysql" Database.MySQL.Base.defaultConnectInfo).

**Comment by paul-rouse** [comment] 2018-06-13 08:32
I agree that the present default is very unfortunate, but I don't think we can simply change it, because migrating an existing database from utf8mb3 to utf8mb4 is not totally straightforward: see the [MySQL Reference Manual](https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-conversion.html).  An optional setting would be fine - would you like to try a PR?

**Comment by alexkazik** [comment] 2018-06-13 09:02
I'd prefer a global option, but I don't see a chance there. I could write createMySQLPoolWithDefaultEncoding and withMySQLConnWithDefaultEncoding which allow you to specify the wanted encoding, and make createMySQLPool an alias for createMySQLPoolWithDefaultEncoding"utf8". What do you think?

**Comment by paul-rouse** [comment] 2018-06-13 09:46
Yes, I think that is how you would have to specify it.  I did wonder about taking the default from the CharsetName option in the ConnectInfo (if it is there at all, falling back to "utf8" if not), but it feels to me as if that would be confusing the connection charset with the default column type.

BTW feel free to send in a PR to https://github.com/paul-rouse/mysql to add `defaultConnectInfoMB4` if you like - the spelling there is meant to be consistent with the `mysql-haskell` package.

**Comment by alexkazik** [comment] 2018-06-13 16:37
I've created a first version: https://github.com/alexkazik/persistent/commit/1d389a1d0808cdd38fa044dd0fa9042b94f155f0

- Is MB4 enough and should *Enc not be added?
- I've added newtype for the default encoding, just to be sure that the type fits, should it be removed?

MockMigration still uses utf8, but since that code is not executed it should be fine.

Haven't tried it in a real project though. The Haskell library mysql always segfauts, I'm using mysql-haskell and persistent-mysql-haskell. I want to add this changes there also.

**Comment by naushadh** [comment] 2018-07-06 23:50
Duplicate of https://github.com/yesodweb/persistent/issues/679

**Comment by alexkazik** [comment] 2018-07-07 10:19
I've created a second version, based upon a discussion on persistent-mysql-haskell.

If the ConnectInfo states that the charset is utf8mb4 then it's also used for the default text types, otherwise still utf8.

https://github.com/alexkazik/persistent/commit/81850ef9648066c4acd14ee6e050a9ea1d555f90

Opinions on either this or the previous idea?

**Comment by parsonsmatt** [comment] 2020-02-14 01:09
Merged in #980

**Closed by parsonsmatt** 2020-02-14 01:09 UTC
