### ISSUE TITLE
Regression

### ISSUE THREAD

**Issue by brandon-leapyear** [yesodweb/persistent#1094] opened 2020-06-23 17:27 UTC
The following model file works in `persistent-template` 2.6.0:
```
Foo

Bar
  field Int
```
But breaks in `persistent-template` 2.8.2.3. Admittedly, this is a bit of a hack that we did to enforce a relationship (since an empty model provides a unique ID), but I thought it'd be worth bringing up anyway. FYI This is easily worked around with
```
Foo
  deriving Show
```

**Comment by parsonsmatt** [comment] 2020-06-23 17:34
This is a duplicate of #1047 

Thanks for the extra work-around!

**Closed by parsonsmatt** 2020-06-23 17:34 UTC

**Comment by brandon-leapyear** [comment] 2020-06-23 17:39
Whoops also forgot to fill in the title haha. For some reason, I couldn't find that issue. Thanks!

**Comment by parsonsmatt** [comment] 2020-06-23 17:39
It took me several search queries to find it! I should update the title so it's easier to find
