### ISSUE TITLE
Canonical use of persistent is not composable

### ISSUE THREAD

**Issue by TomMD** [yesodweb/persistent#1019] opened 2020-01-19 19:09 UTC
The suggested use of Persistent is to leverage the library to define your datatypes and allow it to derive related type classes (namely, `PersistEntity`).  This method is very ridged and prevents use of pre-existing types that might be defined though other means such as code generation, other quasi-quoters, and external packages.

In order to make persistent more flexible we should make a template Haskell function `entityOf :: Name -> Q Expr` that can be used with `makePersist` such as:

    data Person = Person { name :: String, age :: Int }
    makePersist mongoSettings (entityOf ''Person)

**Comment by parsonsmatt** [comment] 2020-01-19 19:34
This is a bit tricky, because you need a way to map column names to SQL column names and also affix any constraint information (eg foreign keys, uniqueness constraints, an ID column, etc). The level of configuration you'd need would end up looking about as verbose as the entity definition syntax, and so it doesn't save you much (if anything) to have this ability vs. defining the database representation type and then a conversion function to your domain type.

It's relatively straightforward to have:

```haskell
data Person = Person { name :: String, age :: Int }

makePersist persistSettings [persistLowerCase|
  PersonDb sql=person
    name String
    age Int
|]

fromDb :: PersonDb -> Person
fromDb PersonDb {..} = Person { name = personName, age = personAge }

toDb :: Person -> PersonDb
toDb Person {..} = PersonDb { personName = name, personAge = age }
```

If the boilerplate is sufficiently nasty, then you can automate it with Template Haskell.

Finally, it's not a great idea to allow your database schema to depend on external dependencies. A major version bump of a dependency could require you to migrate your database or write out all of this boilerplate anyway to maintain backwards compatibility.

I would like to support this pattern, but it's not clear to me that the answer is "TH to automate defining `PersistEntity` and related classes for external datatypes" instead of "TH to automate defining conversion functions between external types and predefined entities."

**Comment by parsonsmatt** [comment] 2020-01-19 19:35
Closing this issue as a duplicate of #612

**Closed by parsonsmatt** 2020-01-19 19:35 UTC
