### ISSUE TITLE
Incorrect shadowed name warning

### ISSUE THREAD

**Issue by erikd** [yesodweb/persistent#1406] opened 2022-06-10 05:38 UTC
For a trivial schema definition (with persistent 2.14.0.1):
```
share
  [ mkPersist sqlSettings
  , mkMigrate "migrateCardanoDb"
  , mkEntityDefList "entityDefs"
  , deriveShowFields
  ]
  [persistLowerCase|

  SchemaVersion
    stageOne Int
    stageTwo Int
    stageThree Int
    deriving Eq
  |]
```
I an getting strange shadowed name warnings like:
```
rc/Cardano/Db/Schema.hs:47:1: error: [-Wname-shadowing, -Werror=name-shadowing]
    This binding for ‘schemaVersionStageTwo’ shadows the existing binding
      defined at src/Cardano/Db/Schema.hs:47:1
   |
47 | share
   | ^^^^^...

src/Cardano/Db/Schema.hs:47:1: error: [-Wname-shadowing, -Werror=name-shadowing]
    This binding for ‘schemaVersionStageThree’ shadows the existing binding
      defined at src/Cardano/Db/Schema.hs:47:1
   |
47 | share
   | ^^^^^...

src/Cardano/Db/Schema.hs:47:1: error: [-Wname-shadowing, -Werror=name-shadowing]
    This binding for ‘schemaVersionStageOne’ shadows the existing binding
      defined at src/Cardano/Db/Schema.hs:47:1
   |
47 | share
   | ^^^^^...

src/Cardano/Db/Schema.hs:47:1: error: [-Wname-shadowing, -Werror=name-shadowing]
    This binding for ‘schemaVersionStageThree’ shadows the existing binding
      defined at src/Cardano/Db/Schema.hs:47:1
   |
47 | share
   | ^^^^^...

src/Cardano/Db/Schema.hs:47:1: error: [-Wname-shadowing, -Werror=name-shadowing]
    This binding for ‘schemaVersionStageOne’ shadows the existing binding
      defined at src/Cardano/Db/Schema.hs:47:1
   |
47 | share
   | ^^^^^...

src/Cardano/Db/Schema.hs:47:1: error: [-Wname-shadowing, -Werror=name-shadowing]
    This binding for ‘schemaVersionStageTwo’ shadows the existing binding
      defined at src/Cardano/Db/Schema.hs:47:1
   |
47 | share
   | ^^^^^...
```
This worked up until version `2.14`. Adding the constraint `persistent < 2.13.3.4` makes it build again.

**Comment by erikd** [comment] 2022-06-10 05:46
I suspect this is related to #1379 but I am not sure of the fix.

**Comment by parsonsmatt** [comment] 2022-06-10 14:29
Good find, thanks for reporting! I'll dig into this

**Comment by parsonsmatt** [comment] 2022-06-10 15:19
Released in 2.14.0.2

**Closed** 2022-06-10 15:18 UTC
Labels: bug

**Comment by brandonchinn178** [comment] 2022-08-25 03:52
FYI For people looking at this after the fact, the bug was introduced in 2.13.3.4

**Comment by merijn** [comment] 2023-01-31 16:26
I think there was a regression or incomplete fix, because I'm seeing this exact same error and same cause (duplicated names in patterns) on 2.14.4, example generated code obtained via `dump-splices`:

```
      Database.Persist.Class.PersistEntity.keyFromRecordM
        = Just
            (\ StepPropValue {stepPropValueVariantId = stepPropValueVariantId,
                              stepPropValueStepId = stepPropValueStepId,
                              stepPropValueProperty = stepPropValueProperty}
               -> ((StepPropValueKey stepPropValueVariantId) stepPropValueStepId)
                    stepPropValueProperty)
```

**Comment by merijn** [comment] 2023-01-31 16:30
I suspect #1460 is too blame, because the code for that fix touches the same code that was touched by this fix?

**Comment by merijn** [comment] 2023-01-31 16:49
Nevermind, 2.14.4.3 has the same issue for me, so it's not #1460 and possibly the original problem wasn't completely fixed?
