### ISSUE TITLE
unhandled error for composite/non id primary keys

### ISSUE THREAD

**Issue by jwaldmann** [yesodweb/persistent#569] opened 2016-06-02 13:43 UTC
I am getting this error 
```
unhandled error for composite/non id primary keys pfilter=In persistList=[] pdef=CompositeDef {compositeFields = [FieldDef {fieldHaskell = HaskellName {unHaskellName = "studentId"}, fieldDB = DBName {unDBName = "SNr"}, fieldType = FTTypeCon Nothing "StudentId", fieldSqlType = SqlOther "SqlType unset for studentId", fieldAttrs = ["sql=SNr"], fieldStrict = True, fieldReference = NoReference},FieldDef {fieldHaskell = HaskellName {unHaskellName = "gruppeId"}, fieldDB = DBName {unDBName = "GNr"}, fieldType = FTTypeCon Nothing "GruppeId", fieldSqlType = SqlOther "SqlType unset for gruppeId", fieldAttrs = ["sql=GNr"], fieldStrict = True, fieldReference = NoReference}], compositeAttrs = []}
```
and I have no idea how to debug this. The error message does not even mention the table's name (but I can guess it from the names of columns - in this case)

model/table looks like
```
Einschreibung sql=stud_grp
  studentId         StudentId            sql=SNr
  gruppeId          GruppeId             sql=GNr
  Primary studentId gruppeId

mysql> describe stud_grp;
+-------+------------+------+-----+---------+-------+
| Field | Type       | Null | Key | Default | Extra |
+-------+------------+------+-----+---------+-------+
| SNr   | bigint(20) | NO   | PRI | NULL    |       |
| GNr   | bigint(20) | NO   | PRI | NULL    |       |
+-------+------------+------+-----+---------+-------+
```
and I confirmed that there are no duplicate rows.

**Comment by gregwebs** [comment] 2016-06-02 16:33
What is the query that you are running? It looks like you provided an empty list for an in query, can you confirm? I can change persistent to surface a better error message.

**Comment by jwaldmann** [comment] 2016-06-02 18:11
In this handler: https://gitlab.imn.htwk-leipzig.de/autotool/all/blob/master/yesod/Handler/Gruppen.hs#L15 

Indeed, occurence of this error depends on other data that's possibly combined in the query. The model is: student is associated with a group, group belongs to a lecture (vorlesung). Error occurs when there are no gruppen for a vorlesung.

**Comment by gregwebs** [comment] 2016-06-02 20:49
I would suggest producing a NonEmpty (I would like to change the API to require that) any time you do an In query. Just call toList on the NonEmpty. A better error message is committed to master now.

**Closed by gregwebs** 2016-06-02 20:49 UTC

**Comment by jwaldmann** [comment] 2016-06-03 16:04
Thanks for the patch. 

What's the easiest way for me to use the patched `persistent` in my (stack) project?
I put this in `stack.yaml`:
```
- location:
    git: https://github.com/yesodweb/persistent
    commit: 5674ad3fb5862b223ba676b229682fe0997240c1
   subdirs:
   - persistent
```
but this leads to
```
--  Failure when adding dependencies:    
      persistent: needed (>=2.1 && <2.3), 2.5 found (latest applicable is 2.2.4.1)
      yesod-form: needed (>=1.4 && <1.5), couldn't resolve its dependencies
```
(and more).

**Comment by jwaldmann** [comment] 2016-06-03 16:08
Am I understanding you right -- the problem with my code
```
gruppen <- runDB $ selectList [GruppeVorlesungId ==. vorlesungId] []
  einschreibungen <- runDB $ selectKeysList [EinschreibungId <-. map (EinschreibungKey authId . entityKey) gruppen] []
```
is that the first query returns an empty result set, so the second query does not work?

**Comment by gregwebs** [comment] 2016-06-03 16:18
yes. If you are using stack you will need to be on a nightly build (you can use one before the switch to GHC 8 if you want) to be able to use the latest version of persistent

**Comment by gregwebs** [comment] 2016-06-03 16:21
Actually, you may not use a nightly if you also add a subdirs entry for persistent-template and your backend (persistent-postgresql or whatever you are using)

**Comment by jwaldmann** [comment] 2016-06-03 16:25
(Anyway, since you explained the reason for the exception, maybe I don't need your patch right now.)

Is this "In query needs NonEmpty" documented someplace? I don't find "NonEmpty" in the docs https://s3.amazonaws.com/haddock.stackage.org/lts-6.1/persistent-2.2.4.1/doc-index-N.html and I don't see a definition of "In query" (and it's hard to search for this).

**Comment by gregwebs** [comment] 2016-06-03 16:32
Yep, you don't need the patch.
search stackage for NonEmpty. The problem is that persistent isn't using it yet, but that doesn't mean you can't.
`<-.` in SQL is usually called `IN`.

**Comment by jwaldmann** [comment] 2016-06-03 17:12
Thanks. I appreciate the quick responses. So I will grep for "<-." I Sorry for the bother, I have very little SQL experience, and the student who wrote the code is no longer officially on this project.
